name: Trigger Jenkins

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  trigger-jenkins:
    runs-on: ubuntu-latest

    steps:
      - name: Trigger Jenkins
        env:
          JENKINS_URL: ${{ secrets.JENKINS_URL }}
          JENKINS_TOKEN: ${{ secrets.JENKINS_TOKEN }}
        run: |
          curl -X POST \
            "$(echo "$JENKINS_URL" | tr -d '\r\n')/buildByToken/build?job=my-flask-app&token=$(echo "$JENKINS_TOKEN" | tr -d '\r\n')"